### ISSUE TITLE
URGENT: test-paper does not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/sp17-i524#183]
this does not work. you need to not do a yaml read, as 

a) sometimes there aer more than on : in a line so you need to use split (...,1)
b) sometimes there are two github usernames and you probably just tkae the first (error later on)
c) please remember that we have project dirs so we need to read from them as not everyone uses the hid space

def _parse_readme(self, path):
        lines = []
        with open(path) as fd:
            for line in fd:
                if ':' in line:
                    lines.append(line.strip())

        return yaml.load('\n'.join(lines))

**Comment by badi** [comment]
closed in #185
