### ISSUE TITLE
issue: changes made into S17-IR-2017 

### ISSUE THREAD

**Issue by narayana1043** [cloudmesh/sp17-i524#221]
@dimitargnikolov 

I made all the required changes. Some places I have introduced new sections and paragraphs to support or backup claims and have provided references for them. I have also added a disadvantages section as requested. Please let me know if any further changes are required to make this look better. I changed the conclusion but I am little not sure if it still needs improvement. Please let me know how can I improve that and I will work on that.

Thanks for showing my mistakes. Your comments were helpful when I was working on making the changes.

veera marni.
S17-IR-2017

**Comment by dimitargnikolov** [comment]
@narayana1043, we were working on the second batch of papers, so I haven't been able to get to this yet. I will work on reviewing the edits to paper 1 this week, and will let you know if anything else is needed. Thanks!

**Comment by narayana1043** [comment]
Thanks!
veera
